### ISSUE TITLE
Craig Walls' Spring AI Playlist is empty

### ISSUE THREAD

**Issue by ogbozoyan** [danvega/awesome-spring-ai#2]
Idk maybe it's not available for me for certain reasons, but link in readme 
[Craig Walls' Spring AI Playlist](https://www.youtube.com/@crwalls) refers to empty channel
<img width="951" alt="Screenshot 2024-11-16 at 22 14 04" src="https://github.com/user-attachments/assets/a38c6e49-4cdd-4105-87b5-9c7265de52d8">

**Comment by danvega** [comment]
Thank you, I have fixed this.
